version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672 # WEB
      - 25676:25676
    volumes:
      - rabbitmq-volume1:/var/log/rabbitmq
      - rabbitmq-volume2:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  rabbitmq-volume1:
    driver: local
  rabbitmq-volume2:
    driver: local

#networks:
#  default:
#    external: true
#    name: default-network
